org: juliocesarnb
service: foodiary-v2-api

plugins:
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  runtime: nodejs22.x
  architecture: arm64
  stage: dev2
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    BUCKET_NAME: !Ref UploadsBucketV3
    MEALS_QUEUE_URL: !Ref MealsQueueV3
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: !Sub "${UploadsBucketV3.Arn}/*"
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource:
            - !GetAtt MealsQueueV3.Arn
            - !GetAtt MealsDLQV3.Arn
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "*"

package:
  individually: true

build:
  esbuild:
    minify: true
    sourcemap: false

functions:
  signin:
    handler: src/functions/signin.handler
    timeout: 30
    memorySize: 256
    events:
      - httpApi:
          method: POST
          path: /signin

  signup:
    handler: src/functions/signup.handler
    timeout: 30
    memorySize: 256
    events:
      - httpApi:
          method: POST
          path: /signup

  me:
    handler: src/functions/me.handler
    timeout: 30
    memorySize: 256
    events:
      - httpApi:
          method: GET
          path: /me

  createMeal:
    handler: src/functions/createMeal.handler
    timeout: 30
    memorySize: 256
    events:
      - httpApi:
          method: POST
          path: /meals

  listMeals:
    handler: src/functions/listMeals.handler
    timeout: 30
    memorySize: 256
    events:
      - httpApi:
          method: GET
          path: /meals

  getMealById:
    handler: src/functions/getMealById.handler
    timeout: 30
    memorySize: 256
    events:
      - httpApi:
          method: GET
          path: /meals/{mealId}

  fileUploadedEvent:
    handler: src/functions/fileUploadedEvent.handler
    timeout: 30
    memorySize: 256
    events:
      - s3:
          bucket: !Ref UploadsBucketV3
          event: s3:ObjectCreated:*
          existing: true

  processMeal:
    handler: src/functions/processMeal.handler
    timeout: 300
    memorySize: 2048
    events:
      - sqs:
          arn: !GetAtt MealsQueueV3.Arn
          batchSize: 1

resources:
  Resources:
    UploadsBucketV3:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: jstacklab-v3-foodiary-uploads

    MealsQueueV3:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: meals-queue-v3
        VisibilityTimeout: 360
        MessageRetentionPeriod: 3600
        RedrivePolicy:
          maxReceiveCount: 3
          deadLetterTargetArn: !GetAtt MealsDLQV3.Arn

    MealsDLQV3:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: meals-queue-v3-dlq
        MessageRetentionPeriod: 1209600