org: juliocesarnb
service: foodiary-v2-api

plugins:
  - serverless-s3-local
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  runtime: nodejs22.x
  architecture: arm64
  stage: dev2 # 👈 novo stage
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    BUCKET_NAME: !Ref UploadsBucketV3
    MEALS_QUEUE_URL: !Ref MealsQueueV3
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: !Sub "${UploadsBucketV3.Arn}/*"
        - Effect: Allow
          Action: sqs:SendMessage
          Resource: !GetAtt MealsQueueV3.Arn

package:
  individually: true

build:
  esbuild:
    minify: true
    sourcemap: false
custom:
  s3:
    host: localhost
    port: 4571
    directory: /tmp
functions:
  signin:
    handler: src/functions/signin.handler
    events:
      - httpApi:
          method: POST
          path: /signin

  signup:
    handler: src/functions/signup.handler
    events:
      - httpApi:
          method: POST
          path: /signup

  me:
    handler: src/functions/me.handler
    events:
      - httpApi:
          method: GET
          path: /me

  createMeal:
    handler: src/functions/createMeal.handler
    events:
      - httpApi:
          method: POST
          path: /meals

  listMeals:
    handler: src/functions/listMeals.handler
    events:
      - httpApi:
          method: GET
          path: /meals

  getMealById:
    handler: src/functions/getMealById.handler
    events:
      - httpApi:
          method: GET
          path: /meals/{mealId}

  fileUploadedEvent:
    handler: src/functions/fileUploadedEvent.handler
    events:
      - s3:
          bucket: !Ref UploadsBucketV3
          event: s3:ObjectCreated:*
          existing: true # 👈 indica bucket existente para evitar conflito

  processMeal:
    handler: src/functions/processMeal.handler
    events:
      - sqs:
          arn: !GetAtt MealsQueueV3.Arn
          batchSize: 1

resources:
  Resources:
    UploadsBucketV3:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: jstacklab-v3-foodiary-uploads # 👈 novo bucket

    MealsQueueV3:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: meals-queue-v3
        VisibilityTimeout: 60
        RedrivePolicy:
          maxReceiveCount: 1
          deadLetterTargetArn: !GetAtt MealsDLQV3.Arn

    MealsDLQV3:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: meals-queue-v3-dlq
